name: admin-frontend
services:
  - name: admin-frontend
    github:
      repo: welintech/admin-frontend
      branch: development
      deploy_on_push: true
    environment_slug: node
    instance_count: 1
    instance_size_slug: basic-xxs
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080" 